# Generated by Django 4.2.19 on 2025-02-17 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(default='none', max_length=10)),
                ('email', models.CharField(default='none', max_length=150)),
                ('category', models.CharField(default='none', max_length=150)),
                ('gender', models.CharField(default='none', max_length=150)),
                ('phone_no', models.CharField(default='none', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
