# Generated by Django 4.2.19 on 2025-02-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Danation',
        ),
    ]
