# Generated by Django 4.2.19 on 2025-02-17 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_property_danation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('title', models.CharField(default='none', max_length=50)),
                ('description', models.TextField(default='none')),
                ('goal', models.CharField(default='none', max_length=20)),
                ('about', models.TextField(default='none')),
                ('summary', models.TextField(default='none')),
                ('challenge', models.TextField(default='none')),
                ('target_one', models.CharField(default='none', max_length=1020)),
                ('target_two', models.CharField(default='none', max_length=1020, null=True)),
                ('target_three', models.CharField(default='none', max_length=1020, null=True)),
                ('target_four', models.CharField(default='none', max_length=1020, null=True)),
                ('target_five', models.CharField(default='none', max_length=1020, null=True)),
                ('target_six', models.CharField(default='none', max_length=1020)),
                ('target_seven', models.CharField(default='none', max_length=1020)),
                ('more_info', models.TextField(default='none')),
                ('image_two', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('image_portriat', models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Danation',
        ),
    ]
