# Generated by Django 5.1.6 on 2025-09-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_donation_amount_donated_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image_three',
            field=models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='location',
            field=models.CharField(default='none', max_length=1020),
        ),
        migrations.AddField(
            model_name='donation',
            name='project_type',
            field=models.CharField(default='none', max_length=1020),
        ),
        migrations.AddField(
            model_name='donation',
            name='website',
            field=models.CharField(default='none', max_length=1020),
        ),
    ]
