# Generated by Django 5.1.6 on 2025-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_donation_image_three_donation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image_four',
            field=models.FileField(blank=True, default='none', upload_to='account_files/profile_photos/'),
        ),
    ]
