# Generated by Django 5.1.6 on 2025-10-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_donation_image_four'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('investor', 'Investor'), ('business_owner', 'Business Owner')], default='investor', max_length=20),
        ),
    ]
